INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL) VALUES(TRUE, 'Admin', 'Istrator', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'admin', 'admin', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'ADMIN')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('admin', 'EMPLOYEE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('admin', 'TEMP')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('admin', 'FEELS_LIKE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('admin', 'DESCRIPTION')

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL) VALUES(TRUE, 'Susi', 'Kaufgern', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'user1', 'admin', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('user1', 'MANAGER')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('user1', 'EMPLOYEE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('user1', 'TEMP')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('user1', 'FEELS_LIKE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('user1', 'DESCRIPTION')

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL) VALUES(TRUE, 'Max', 'Mustermann', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'user2', 'admin', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('user2', 'EMPLOYEE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('user2', 'TEMP')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('user2', 'FEELS_LIKE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('user2', 'DESCRIPTION')


INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL) VALUES(TRUE, 'Elvis', 'The King', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'elvis', 'elvis', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'ADMIN')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('elvis', 'EMPLOYEE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('elvis', 'TEMP')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('elvis', 'FEELS_LIKE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('elvis', 'DESCRIPTION')



INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL) VALUES(TRUE, 'Franz', 'Kafka', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'kafka', 'admin', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('kafka', 'ADMIN')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('kafka', 'EMPLOYEE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('kafka', 'TEMP')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('kafka', 'FEELS_LIKE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('kafka', 'DESCRIPTION')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('kafka', 'UVI')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('kafka', 'SUNSET')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('kafka', 'SUNRISE')




INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, PREMIUM_SINCE, EMAIL) VALUES(TRUE, 'Test', 'Premium', '$2a$12$scSaBPNgfRiAy3B91EG8xum/73VgTFrTD3r5U8gF8VrKMoSYbJs3S', 'testPremium', 'admin', '2016-01-02 00:00:00', '2016-01-02 00:00:00',  'swaprojektarbeitwetterapp@gmail.com')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('testPremium', 'PREMIUM')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('testPremium', 'EMPLOYEE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('testPremium', 'TEMP')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('testPremium', 'FEELS_LIKE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('testPremium', 'DESCRIPTION')

INSERT INTO CREDIT_CARD (BALANCE, CREDIT_CARD, USER_ID) VALUES('10', '3475298374', 'testPremium')
INSERT INTO INVOICE (INVOICE_OPEN, CREATE_DATE, INVOICE_ID, USER_ID) VALUES(FALSE, '2024-01-02 00:00:00', '874873573', 'testPremium')

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, PREMIUM_SINCE, EMAIL) VALUES(TRUE, 'Test', 'PremiumBad', '$2a$12$scSaBPNgfRiAy3B91EG8xum/73VgTFrTD3r5U8gF8VrKMoSYbJs3S', 'testPremiumBad', 'admin', '2016-01-02 00:00:00', '2016-01-02 00:00:00',  'swaprojektarbeitwetterapp@gmail.com')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('testPremiumBad', 'PREMIUM')
INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES) VALUES ('testPremiumBad', 'EMPLOYEE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('testPremiumBad', 'TEMP')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('testPremiumBad', 'FEELS_LIKE')
INSERT INTO USERX_SELECTEDFIELDS (USERX_USERNAME, SELECTEDFIELD) VALUES ('testPremiumBad', 'DESCRIPTION')

INSERT INTO CREDIT_CARD (BALANCE, CREDIT_CARD, USER_ID) VALUES('0', '7659656959', 'testPremiumBad')
INSERT INTO INVOICE (INVOICE_OPEN, CREATE_DATE, INVOICE_ID, USER_ID) VALUES(TRUE, '2024-01-02 00:00:00', '7659656959', 'testPremiumBad')
