INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL)
VALUES(TRUE, 'Admin', 'Istrator', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'admin', 'admin', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com');

INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)
VALUES ('admin', 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)
VALUES ('admin', 'EMPLOYEE');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL)
VALUES(TRUE, 'Susi', 'Kaufgern', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'user1', 'admin', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com');

INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)
VALUES ('user1', 'MANAGER');

INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)
VALUES ('user1', 'EMPLOYEE');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL)
VALUES(TRUE, 'Max', 'Mustermann', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'user2', 'admin', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com');

INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)
VALUES ('user2', 'EMPLOYEE');

INSERT INTO USERX (ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_USERNAME, CREATE_DATE, EMAIL)
VALUES(TRUE, 'Elvis', 'The King', '$2a$12$CBvmS9HQHZoSanUlLJDwKu8sdPfJn3dbBnziaJBCNW8HdBPWBz6IC', 'elvis', 'elvis', '2016-01-01 00:00:00', 'swaprojektarbeitwetterapp@gmail.com');

INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)
VALUES ('elvis', 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_USERNAME, ROLES)
VALUES ('elvis', 'EMPLOYEE');